In [16]:
import numpy as np

# Subway ridership for 5 stations on 10 different days
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

In [17]:
print ridership[1, 3]
print ridership[1:3, 3:5]
print ridership[1, :]

2328
[[2328 2539]
 [6461 2691]]
[1478 3877 3674 2328 2539]


In [18]:
print ridership[0, :] + ridership[1, :]
print ridership[:, 0] + ridership[:, 1]

[1478 3877 3676 2333 2539]
[   0 5355 5701 4952 6410 5509  324    2 5223 5385]


In [19]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
print a + b

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [21]:
def mean_riders_for_max_station(ridership):
    '''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    
    Hint: NumPy's argmax() function might be useful:
    http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html
    '''
    
    overall_mean = ridership.mean()
    max_station = ridership[0, :].argmax()
    mean_for_max = ridership[:, max_station].mean()
    
    return (overall_mean, mean_for_max)

In [22]:
mean_riders_for_max_station(ridership)

(2342.5999999999999, 3239.9000000000001)

In [23]:
a = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ])
    
print a.sum()
print a.sum(axis=0)
print a.sum(axis=1)

45
[12 15 18]
[ 6 15 24]


In [24]:
def min_and_max_riders_per_day(ridership):
    '''
    Fill in this function. First, for each subway station, calculate the
    mean ridership per day. Then, out of all the subway stations, return the
    maximum and minimum of these values. That is, find the maximum
    mean-ridership-per-day and the minimum mean-ridership-per-day for any
    subway station.
    '''
    daily_ridership = ridership.mean(axis=0)
    max_daily_ridership = daily_ridership.max()     # Replace this with your code
    min_daily_ridership = daily_ridership.min()     # Replace this with your code
    
    return (max_daily_ridership, min_daily_ridership)

In [25]:
min_and_max_riders_per_day(ridership)

(3239.9000000000001, 1071.2)

In [26]:
import pandas as pd

df_1 = pd.DataFrame({'A': [0, 1, 2], 'B': [3, 4, 5]})
print df_1

   A  B
0  0  3
1  1  4
2  2  5


In [27]:
df_2 = pd.DataFrame([[0, 1, 2], [3, 4, 5]], columns=['A', 'B', 'C'])
print df_2

   A  B  C
0  0  1  2
1  3  4  5


In [28]:
ridership_df = pd.DataFrame(
    data=[[   0,    0,    2,    5,    0],
          [1478, 3877, 3674, 2328, 2539],
          [1613, 4088, 3991, 6461, 2691],
          [1560, 3392, 3826, 4787, 2613],
          [1608, 4802, 3932, 4477, 2705],
          [1576, 3933, 3909, 4979, 2685],
          [  95,  229,  255,  496,  201],
          [   2,    0,    1,   27,    0],
          [1438, 3785, 3589, 4174, 2215],
          [1342, 4043, 4009, 4665, 3033]],
    index=['05-01-11', '05-02-11', '05-03-11', '05-04-11', '05-05-11',
           '05-06-11', '05-07-11', '05-08-11', '05-09-11', '05-10-11'],
    columns=['R003', 'R004', 'R005', 'R006', 'R007']
)

In [29]:
print ridership_df.iloc[0]
print ridership_df.loc['05-05-11']
print ridership_df['R003']
print ridership_df.iloc[1, 3]

R003    0
R004    0
R005    2
R006    5
R007    0
Name: 05-01-11, dtype: int64
R003    1608
R004    4802
R005    3932
R006    4477
R007    2705
Name: 05-05-11, dtype: int64
05-01-11       0
05-02-11    1478
05-03-11    1613
05-04-11    1560
05-05-11    1608
05-06-11    1576
05-07-11      95
05-08-11       2
05-09-11    1438
05-10-11    1342
Name: R003, dtype: int64
2328


In [30]:
print ridership_df.iloc[1:4]

          R003  R004  R005  R006  R007
05-02-11  1478  3877  3674  2328  2539
05-03-11  1613  4088  3991  6461  2691
05-04-11  1560  3392  3826  4787  2613


In [31]:
print ridership_df[['R003', 'R005']]

          R003  R005
05-01-11     0     2
05-02-11  1478  3674
05-03-11  1613  3991
05-04-11  1560  3826
05-05-11  1608  3932
05-06-11  1576  3909
05-07-11    95   255
05-08-11     2     1
05-09-11  1438  3589
05-10-11  1342  4009


In [43]:
df = pd.DataFrame({'A': [0, 1, 2], 'B': [3, 4, 5]})
print df.sum()
print df.sum(axis=1)
print df.values.sum()

A     3
B    12
dtype: int64
0    3
1    5
2    7
dtype: int64
15


In [48]:
def mean_riders_for_max_station(ridership_df):
    '''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    
    This is the same as a previous exercise, but this time the
    input is a Pandas DataFrame rather than a 2D NumPy array.
    '''
    max_station = ridership_df.iloc[0].argmax()
    overall_mean = ridership_df.mean() # Replace this with your code
    mean_for_max = ridership_df[max_station].mean() # Replace this with your code
    
    return (overall_mean, mean_for_max)

In [49]:
mean_riders_for_max_station(ridership_df)

(R003    1071.2
 R004    2814.9
 R005    2718.8
 R006    3239.9
 R007    1868.2
 dtype: float64, 3239.9)

In [50]:
subway_df = pd.read_csv('nyc-subway-weather.csv')

In [51]:
subway_df.head()

UNIT     DATEn     TIMEn  ENTRIESn   EXITSn  ENTRIESn_hourly  \
0  R003  05-01-11  00:00:00   4388333  2911002              0.0   
1  R003  05-01-11  04:00:00   4388333  2911002              0.0   
2  R003  05-01-11  12:00:00   4388333  2911002              0.0   
3  R003  05-01-11  16:00:00   4388333  2911002              0.0   
4  R003  05-01-11  20:00:00   4388333  2911002              0.0   

   EXITSn_hourly             datetime  hour  day_week     ...       pressurei  \
0            0.0  2011-05-01 00:00:00     0         6     ...           30.22   
1            0.0  2011-05-01 04:00:00     4         6     ...           30.25   
2            0.0  2011-05-01 12:00:00    12         6     ...           30.28   
3            0.0  2011-05-01 16:00:00    16         6     ...           30.26   
4            0.0  2011-05-01 20:00:00    20         6     ...           30.28   

  rain  tempi  wspdi meanprecipi  meanpressurei  meantempi  meanwspdi  \
0    0   55.9    3.5         0.0         30.258      55.98       7.86   
1    0   52.0    3.5         0.0         30.258      55.98       7.86   
2    0   62.1    6.9         0.0         30.258      55.98       7.86   
3    0   57.9   15.0         0.0         30.258      55.98       7.86   
4    0   52.0   10.4         0.0         30.258      55.98       7.86   

   weather_lat  weather_lon  
0    40.700348   -73.887177  
1    40.700348   -73.887177  
2    40.700348   -73.887177  
3    40.700348   -73.887177  
4    40.700348   -73.887177  

[5 rows x 27 columns]

In [52]:
subway_df.describe()

ENTRIESn        EXITSn  ENTRIESn_hourly  EXITSn_hourly  \
count  4.264900e+04  4.264900e+04     42649.000000   42649.000000   
mean   2.812486e+07  1.986993e+07      1886.589955    1361.487866   
std    3.043607e+07  2.028986e+07      2952.385585    2183.845409   
min    0.000000e+00  0.000000e+00         0.000000       0.000000   
25%    1.039762e+07  7.613712e+06       274.000000     237.000000   
50%    1.818389e+07  1.331609e+07       905.000000     664.000000   
75%    3.263049e+07  2.393771e+07      2255.000000    1537.000000   
max    2.357746e+08  1.493782e+08     32814.000000   34828.000000   

               hour      day_week       weekday      latitude     longitude  \
count  42649.000000  42649.000000  42649.000000  42649.000000  42649.000000   
mean      10.046754      2.905719      0.714436     40.724647    -73.940364   
std        6.938928      2.079231      0.451688      0.071650      0.059713   
min        0.000000      0.000000      0.000000     40.576152    -74.073622   
25%        4.000000      1.000000      0.000000     40.677107    -73.987342   
50%       12.000000      3.000000      1.000000     40.717241    -73.953459   
75%       16.000000      5.000000      1.000000     40.759123    -73.907733   
max       20.000000      6.000000      1.000000     40.889185    -73.755383   

                fog      ...          pressurei          rain         tempi  \
count  42649.000000      ...       42649.000000  42649.000000  42649.000000   
mean       0.009824      ...          29.971096      0.224741     63.103780   
std        0.098631      ...           0.137942      0.417417      8.455597   
min        0.000000      ...          29.550000      0.000000     46.900000   
25%        0.000000      ...          29.890000      0.000000     57.000000   
50%        0.000000      ...          29.960000      0.000000     61.000000   
75%        0.000000      ...          30.060000      0.000000     69.100000   
max        1.000000      ...          30.320000      1.000000     86.000000   

              wspdi   meanprecipi  meanpressurei     meantempi     meanwspdi  \
count  42649.000000  42649.000000   42649.000000  42649.000000  42649.000000   
mean       6.927872      0.004618      29.971096     63.103780      6.927872   
std        4.510178      0.016344       0.131158      6.939011      3.179832   
min        0.000000      0.000000      29.590000     49.400000      0.000000   
25%        4.600000      0.000000      29.913333     58.283333      4.816667   
50%        6.900000      0.000000      29.958000     60.950000      6.166667   
75%        9.200000      0.000000      30.060000     67.466667      8.850000   
max       23.000000      0.157500      30.293333     79.800000     17.083333   

        weather_lat   weather_lon  
count  42649.000000  42649.000000  
mean      40.728555    -73.938693  
std        0.065420      0.059582  
min       40.600204    -74.014870  
25%       40.688591    -73.985130  
50%       40.720570    -73.949150  
75%       40.755226    -73.912033  
max       40.862064    -73.694176  

[8 rows x 21 columns]

In [53]:
def correlation(x, y):
    std_x = (x - x.mean()) / x.std(ddof=0)
    std_y = (y - x.mean()) / y.std(ddof=0)
    
    return (std_x * std_y).mean()

In [54]:
entries = subway_df['ENTRIESn_hourly']
cum_entries = subway_df['ENTRIESn']
rain = subway_df['meanprecipi']
temp = subway_df['meantempi']

print correlation(entries, rain)
print correlation(entries, temp)
print correlation(rain, temp)

print correlation(entries, cum_entries)

0.0356485157085
-0.0266933483216
-0.229034323408
0.585895470766


In [55]:
df1 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]})
df2 = pd.DataFrame({'a': [10, 20, 30], 'b': [40, 50, 60], 'c': [70, 80, 90]})
print df1 + df2

    a   b   c
0  11  44  77
1  22  55  88
2  33  66  99


In [56]:
df1 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]})
df2 = pd.DataFrame({'d': [10, 20, 30], 'c': [40, 50, 60], 'b': [70, 80, 90]})
print df1 + df2

    a   b   c   d
0 NaN  74  47 NaN
1 NaN  85  58 NaN
2 NaN  96  69 NaN


In [57]:
df1 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]},
                       index=['row1', 'row2', 'row3'])
df2 = pd.DataFrame({'a': [10, 20, 30], 'b': [40, 50, 60], 'c': [70, 80, 90]},
                       index=['row4', 'row3', 'row2'])
print df1 + df2

         a     b     c
row1   NaN   NaN   NaN
row2  32.0  65.0  98.0
row3  23.0  56.0  89.0
row4   NaN   NaN   NaN


In [58]:
entries_and_exits = pd.DataFrame({
    'ENTRIESn': [3144312, 3144335, 3144353, 3144424, 3144594,
                 3144808, 3144895, 3144905, 3144941, 3145094],
    'EXITSn': [1088151, 1088159, 1088177, 1088231, 1088275,
               1088317, 1088328, 1088331, 1088420, 1088753]
})

In [59]:
def get_hourly_entries_and_exits(entries_and_exits):
    '''
    Fill in this function to take a DataFrame with cumulative entries
    and exits (entries in the first column, exits in the second) and
    return a DataFrame with hourly entries and exits (entries in the
    first column, exits in the second).
    '''
    return entries_and_exits - entries_and_exits.shift(1)

In [60]:
get_hourly_entries_and_exits(entries_and_exits)

ENTRIESn  EXITSn
0       NaN     NaN
1      23.0     8.0
2      18.0    18.0
3      71.0    54.0
4     170.0    44.0
5     214.0    42.0
6      87.0    11.0
7      10.0     3.0
8      36.0    89.0
9     153.0   333.0

In [61]:
def get_hourly_entries_and_exits2(entries_and_exits):
    '''
    Fill in this function to take a DataFrame with cumulative entries
    and exits (entries in the first column, exits in the second) and
    return a DataFrame with hourly entries and exits (entries in the
    first column, exits in the second).
    '''
    return entries_and_exits.diff()

In [62]:
get_hourly_entries_and_exits2(entries_and_exits)

ENTRIESn  EXITSn
0       NaN     NaN
1      23.0     8.0
2      18.0    18.0
3      71.0    54.0
4     170.0    44.0
5     214.0    42.0
6      87.0    11.0
7      10.0     3.0
8      36.0    89.0
9     153.0   333.0

In [63]:
df = pd.DataFrame({
        'a': [1, 2, 3],
        'b': [10, 20, 30],
        'c': [5, 10, 15]
    })
    
def add_one(x):
    return x + 1
        
print df.applymap(add_one)

   a   b   c
0  2  11   6
1  3  21  11
2  4  31  16


In [64]:
grades_df = pd.DataFrame(
    data={'exam1': [43, 81, 78, 75, 89, 70, 91, 65, 98, 87],
          'exam2': [24, 63, 56, 56, 67, 51, 79, 46, 72, 60]},
    index=['Andre', 'Barry', 'Chris', 'Dan', 'Emilio', 
           'Fred', 'Greta', 'Humbert', 'Ivan', 'James']
)

In [65]:
def convert_grade(grades):
    '''
    Fill in this function to convert the given DataFrame of numerical
    grades to letter grades. Return a new DataFrame with the converted
    grade.
    
    The conversion rule is:
        90-100 -> A
        80-89  -> B
        70-79  -> C
        60-69  -> D
        0-59   -> F
    '''
    if grades >= 90 and grades <= 100:
        return 'A'
    elif grades >= 80 and grades < 90:
        return 'B'
    elif grades >= 70 and grades < 80:
        return 'C'
    elif grades >= 60 and grades < 70:
        return 'D'
    return 'F'

In [66]:
def convert_grades(grades):
    return grades.applymap(convert_grade)

In [67]:
convert_grades(grades_df)

exam1 exam2
Andre       F     F
Barry       B     D
Chris       C     F
Dan         C     F
Emilio      B     D
Fred        C     F
Greta       A     C
Humbert     D     F
Ivan        A     C
James       B     D

In [68]:
def convert_grades_curve(exam_grades):
        # Pandas has a bult-in function that will perform this calculation
        # This will give the bottom 0% to 10% of students the grade 'F',
        # 10% to 20% the grade 'D', and so on. You can read more about
        # the qcut() function here:
        # http://pandas.pydata.org/pandas-docs/stable/generated/pandas.qcut.html
        return pd.qcut(exam_grades,
                       [0, 0.1, 0.2, 0.5, 0.8, 1],
                       labels=['F', 'D', 'C', 'B', 'A'])
        
# qcut() operates on a list, array, or Series. This is the
# result of running the function on a single column of the
# DataFrame.
print convert_grades_curve(grades_df['exam1'])

# qcut() does not work on DataFrames, but we can use apply()
# to call the function on each column separately
print grades_df.apply(convert_grades_curve)

Andre      F
Barry      B
Chris      C
Dan        C
Emilio     B
Fred       C
Greta      A
Humbert    D
Ivan       A
James      B
Name: exam1, dtype: category
Categories (5, object): [A < B < C < D < F]
        exam1 exam2
Andre       F     F
Barry       B     B
Chris       C     C
Dan         C     C
Emilio      B     B
Fred        C     C
Greta       A     A
Humbert     D     D
Ivan        A     A
James       B     B


In [69]:
def standardize_column(column):
    return (column - column.mean()) / column.std()

In [70]:
def standardize(df):
    '''
    Fill in this function to standardize each column of the given
    DataFrame. To standardize a variable, convert each value to the
    number of standard deviations it is above or below the mean.
    '''
    return df.apply(standardize_column)

In [71]:
standardize(grades_df)

exam1     exam2
Andre   -2.196525 -2.186335
Barry    0.208891  0.366571
Chris    0.018990 -0.091643
Dan     -0.170911 -0.091643
Emilio   0.715295  0.628408
Fred    -0.487413 -0.418938
Greta    0.841896  1.413917
Humbert -0.803916 -0.746234
Ivan     1.284999  0.955703
James    0.588694  0.170194